---

- name: Webserver setup
  hosts: webservers
  become: yes
  tasks:
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start the service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes

- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MariaDB on Ubuntu
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present
        update_cache: yes

    - name: Start MariaDB  service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes
