---
- name: DBserver setup
  hosts: dbservers
  become: yes
  tasks:
    - name: Install MariaDB on Ubuntu
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present
        update_cache: yes

    - name: Install PyMQL
      apt:
        name:
          - python3-mysqldb
        state: present
        update_cache: yes

    - name: Start MariaDB  service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
            name: bobdata
            state: present

    - name: Create database user with name 'Leonel'
      mysql_user:
            name: Leonel
            password: 'admin943'
            priv: '*.*:ALL'
            state: present
