---
- name: Understanding vars
  hosts: all
  become: yes
  gather_facts: False
    #vars:
    #USRNM: playuser
    #COMM: variable from playbook
  tasks:
    - name: create user
      ansible.builtin.user:
           name: "{{USRNM}}"
           comment: "{{COMM}}"
      register: result

    - debug:
       var: result.name
    - debug:
        var: result.comment
